
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 12 20:06:57 COT 2015
//----------------------------------------------------

package archivojflex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 4;
  public static final int error = 1;
  public static final int PC = 2;
  public static final int TRADUCIR = 3;
  public static final int EOF = 0;
}

